# 🕒 Pandas 时间处理 (Datetime) 实战演练

很多时候我们从 Excel 或 CSV 读入的数据，时间只是一串“死”的字符串。我们要先把它“激活”成 Pandas 认识的时间对象，然后才能像捏橡皮泥一样提取年份、月份、周几。

---
### 1. 准备一份带有“死字符串”的数据

In [1]:
import pandas as pd

# 假设这是从系统导出的订单数据，'下单时间' 现在只是普通的文字 (String/Object)
data = {
    '订单号': ['A001', 'A002', 'A003', 'A004'],
    '下单时间': ['2023-01-15 10:30:00', '2023-05-20 14:00:00', '2024-02-14 09:15:00', '2024-03-23 18:45:00'],
    '金额': [100, 250, 180, 420]
}
df = pd.DataFrame(data)

print("--- 转换前的类型 ---")
print(df.dtypes)
df.head()

--- 转换前的类型 ---
订单号     object
下单时间    object
金额       int64
dtype: object

    订单号                 下单时间   金额
0  A001  2023-01-15 10:30:00  100
1  A002  2023-05-20 14:00:00  250
2  A003  2024-02-14 09:15:00  180
3  A004  2024-03-23 18:45:00  420

### 2. “激活”时间列 (点石成金)

现在的 `下单时间` 是 `object`（也就是文本）。我们无法直接问它“这天是周几”。
我们要用 `pd.to_datetime()` 将其转化为 `datetime64` 类型。

In [2]:
# 激活它！
df['下单时间'] = pd.to_datetime(df['下单时间'])

print("--- 转换后的类型 ---")
print(df.dtypes)  # 现在下单时间变成了 datetime64[ns]
df.head()

--- 转换后的类型 ---
订单号             object
下单时间    datetime64[ns]
金额               int64
dtype: object

    订单号                下单时间   金额
0  A001 2023-01-15 10:30:00  100
1  A002 2023-05-20 14:00:00  250
2  A003 2024-02-14 09:15:00  180
3  A004 2024-03-23 18:45:00  420

### 3. 使用 `.dt` 提取时间零件 (降维打击)

既然已经激活成 `datetime64` 了，你就可以通过 `.dt` 这个超能力前缀，随意提取任何你想要的信息。

常见属性：
* `.dt.year`: 年份
* `.dt.month`: 月份
* `.dt.day`: 日
* `.dt.hour`: 小时
* `.dt.dayofweek`: 星期几 (0=周一, 6=周日)
* `.dt.date`: 纯日期 (去掉时分秒)

In [3]:
# 尝试提取
df['年份'] = df['下单时间'].dt.year
df['月份'] = df['下单时间'].dt.month
df['小时'] = df['下单时间'].dt.hour
df['星期几'] = df['下单时间'].dt.dayofweek # 注意：0 是周一

# 如果你要看具体是周几，还可以这么转：
# df['星期名称'] = df['下单时间'].dt.day_name()

df.head()

    订单号                下单时间   金额    年份  月份  小时  星期几
0  A001 2023-01-15 10:30:00  100  2023   1  10    6
1  A002 2023-05-20 14:00:00  250  2023   5  14    5
2  A003 2024-02-14 09:15:00  180  2024   2   9    2
3  A004 2024-03-23 18:45:00  420  2024   3  18    5